spring:
  data:
    mongodb:
      uri: mongodb+srv://sairam356:sairam356@cluster0.psnnnhy.mongodb.net/test
     
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: jbansode23@gmail.com
    password: gujzwguujmeetory
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false

logging:
  level:
    root: DEBUG

    
server:
  port: 9191
  
app:
  banking-service:
    url: http://localhost:9292/bank